name: ggomdol_pedometer
description: A Pedometer and Step Detection package for Android and iOS. Step count is streamed as the platform updates it.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ggomdol.pedometer
        pluginClass: PedometerPlugin
      ios:
        pluginClass: PedometerPlugin
