name: ggomdol_pedometer
description: This plugin allows for Query the number of steps count collected over 7 days on AOS and IOS.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ggomdol.pedometer
        pluginClass: PedometerPlugin
      ios:
        pluginClass: PedometerPlugin
